### ISSUE TITLE
`.truthy` and `.falsey` instead of `.true` and `.false`?

### ISSUE THREAD

**Issue by tunnckoCore** [kevva/claim#3]
I think it's more correct.

**Comment by sindresorhus** [comment]
No, they actually check strictly: https://github.com/kevva/claim/blob/1f463081091e6302e4808b98d0e965a89f3add2b/index.js#L27

But it might be worth to have `.ok()` and `notOk()` methods for truthy/falsey => https://github.com/kevva/claim/issues/5

**Comment by tunnckoCore** [comment]
Mm nope? `val` from the given line goes to the `test()` in which it is set directly to the `if` statement, so just truthy values. The `.is` and `.not` are strict equalities.

https://github.com/substack/tape#tokvalue-msg as you suggest in #5 

`.true()` and `.truthy()` are aliases
