### ISSUE TITLE
Name of `.error()` method

### ISSUE THREAD

**Issue by arthurvr** [kevva/claim#6]
I find the `.error()` name kinda confusing. I would expect that it checks if something is an `Error`, while in fact it checks if something is falsey (isn't an error). Maybe `ifError` is clearer? Any other suggestions?

**Comment by sindresorhus** [comment]
The Node.js core `assert` module also uses `ifError` so I think that's a good choice. Could also go with `ifErr`. We can keep this open for a little while in case anyone comes up with something better.

**Comment by tunnckoCore** [comment]
:+1: for `.ifError` and maybe with `.ifErr` alias. But i think `ifError` is enough and convenient.
