### ISSUE TITLE
instanceOf()

### ISSUE THREAD

**Issue by Qix-** [kevva/claim#8]
Need `instanceOf()`!

**Comment by sindresorhus** [comment]
I honestly never use `instanceof`. What do you use it for?

We might pass on this unless there's strong opinions otherwise as we're trying to keep this module small and focused. Can always use heavier assertion libs if you need something like this. Keeping it open for discussion though.

**Comment by arthurvr** [comment]
Yeah, me neighter. I practically never use it.

**Comment by tunnckoCore** [comment]
> Yeah, me neighter. I practically never use it.

:+1: Only place i use it is `assert.throws(fn, TypeError) + assert.throws(fn, msg)` combo.

**Comment by Qix-** [comment]
``` javascript
async.each([1, 2, 3], function (cb) {
  claim.instanceOf(cb, Function); // make sure async is correctly passing me a function callback
});
```

Obviously I'm not writing tests for `async`, but I over-test my frameworks to make sure they're giving me exactly what I'm expecting.

**Comment by tunnckoCore** [comment]
why not?

``` js
async.each([1, 2, 3], function (cb) {
  claim.is(cb instanceof Function, true); // make sure async is correctly passing me a function callback
});
```

**Comment by Qix-** [comment]
For the same reason

``` javascript
claim.is(1, 1);
```

instead of

``` javascript
claim.true(1 === 1)
```

**Comment by sindresorhus** [comment]
@Qix- 

`claim.instanceOf(cb, Function);` → `claim.is(typeof cb, 'function');`

You shouldn't use `instanceof` with Function as it won't work if it comes from another realm like windows/frames in the browser. And with `typeof`, you can just use `.is()`.

**Comment by Qix-** [comment]
@sindresorhus I understand, though in Node in particular that isn't a problem. If I need to check `instanceof` for anything, not even Functions in particular, then I have to use instanceof. `claim` could even do

``` javascript
claim.instanceOf(obj, SomeFunction); // obj.constructor.name === SomeFunction.name
```

Using `.is()` defeats the purpose of a library re-creating these methods for better error output, right?

**Comment by sindresorhus** [comment]
Seeing as this is IMHO and obscure case, I'd prefer we go with `power-assert` on this one.

``` js
claim.ok(obj instanceOf SomeFunction);
```

https://github.com/sindresorhus/ava/pull/46

**Comment by Qix-** [comment]
Agreed with that.
