### ISSUE TITLE
And/or checking?

### ISSUE THREAD

**Issue by Qix-** [kevva/claim#9]
Need to be able to say _this_ **or** _this, or *this_ **and** _this_. Sometimes assertions don't make sense without two checks, and having to work around by doing `claim.true(x && y, true)` is less than ideal.

**Comment by sindresorhus** [comment]
Can you provide an example usage of how it would look?

**Comment by Qix-** [comment]
`claim.true(x).and.false(y)`

**Comment by sindresorhus** [comment]
`claim.true(x).and.false(y);` is the same as `claim.true(x); claim.false(y);` though.

I have honestly never needed something like `or`, but I would rather see it supported through `power-assert`. So you can just do `t.ok(x || y)` and have `power-assert` handle the nice output.

https://github.com/sindresorhus/ava/pull/46

**Comment by Qix-** [comment]
Another :+1: for `power-assert`.
